import json
import platform
import re
import subprocess
import sys
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent.parent
REQUIREMENTS_FILE = PROJECT_ROOT / "backend" / "requirements.txt"


def run_command(command):
    try:
        result = subprocess.run(
            command,
            capture_output=True,
            text=True,
            timeout=10,
            shell=False,
        )

        if result.returncode == 0:
            return result.stdout.strip()

    except Exception:
        pass

    return None


def detect_cpu():
    cpu = platform.processor()

    if not cpu:
        cpu = "Unknown CPU"

    return cpu


def detect_ram():
    try:
        import psutil

        return round(psutil.virtual_memory().total / (1024 ** 3), 1)

    except Exception:
        return None


def detect_nvidia():
    """
    Detect NVIDIA GPU using nvidia-smi.

    This works BEFORE PyTorch is installed.
    """

    output = run_command(
        [
            "nvidia-smi",
            "--query-gpu=name,memory.total,driver_version",
            "--format=csv,noheader,nounits",
        ]
    )

    if not output:
        return {
            "available": False,
            "name": None,
            "vram_gb": None,
            "driver": None,
        }

    line = output.splitlines()[0]

    parts = [x.strip() for x in line.split(",")]

    if len(parts) < 3:
        return {
            "available": False,
            "name": None,
            "vram_gb": None,
            "driver": None,
        }

    name = parts[0]

    try:
        vram_mb = float(parts[1])
        vram_gb = round(vram_mb / 1024, 1)
    except Exception:
        vram_gb = None

    driver = parts[2]

    return {
        "available": True,
        "name": name,
        "vram_gb": vram_gb,
        "driver": driver,
    }


def detect_cuda_capability():
    """
    RTX 3060 Ti / RTX 30 series:
    Compute Capability = 8.6

    This function tries to get the capability from an existing
    CUDA-enabled PyTorch installation.
    """

    try:
        import torch

        if torch.cuda.is_available():
            capability = torch.cuda.get_device_capability(0)

            return f"{capability[0]}.{capability[1]}"

    except Exception:
        pass

    return None


def choose_backend(nvidia):
    if nvidia["available"]:
        return {
            "backend": "cuda",
            "torch_version": "2.6.0+cu124",
            "torchaudio_version": "2.6.0+cu124",
            "torch_index_url": "https://download.pytorch.org/whl/cu124",
        }

    return {
        "backend": "cpu",
        "torch_version": "2.6.0",
        "torchaudio_version": "2.6.0",
        "torch_index_url": "https://download.pytorch.org/whl/cpu",
    }


def generate_requirements(config):
    backend = config["backend"]

    if backend == "cuda":
        torch_lines = [
            "torch==2.6.0+cu124",
            "torchaudio==2.6.0+cu124",
            "--extra-index-url https://download.pytorch.org/whl/cu124",
        ]
    else:
        torch_lines = [
            "torch==2.6.0",
            "torchaudio==2.6.0",
            "--extra-index-url https://download.pytorch.org/whl/cpu",
        ]

    requirements = f"""# Local AI Voice Studio — Backend Dependencies
# =============================================
# AUTO-GENERATED BY scripts/detect_hardware.py
#
# Hardware:
# CPU: {config["cpu"]}
# RAM: {config["ram_gb"]} GB
# GPU: {config["gpu_name"] or "None"}
# VRAM: {config["vram_gb"] or "N/A"} GB
# NVIDIA Driver: {config["nvidia_driver"] or "N/A"}
# Backend: {backend}
#
# DO NOT manually change the PyTorch lines.
# Run scripts\\install.bat to regenerate them.

# Core
fastapi>=0.115.0
uvicorn[standard]>=0.34.0
python-multipart>=0.0.9
pydantic>=2.0
pyyaml>=6.0
aiofiles>=24.0
sse-starlette>=2.0

# Chatterbox compatibility
chatterbox-tts==0.1.7
setuptools==69.5.1

# PyTorch
{chr(10).join(torch_lines)}

# Other TTS
kokoro>=0.9.4
soundfile>=0.12
misaki[ja]

# Audio Processing
librosa>=0.10
pydub>=0.25
numpy>=1.24

# System Detection
psutil>=5.9
GPUtil>=1.4

# Model Management
huggingface-hub>=0.20

# Testing
pytest>=8.0
pytest-asyncio>=0.23
httpx>=0.27

# Optional: Piper TTS
# piper-tts
"""

    REQUIREMENTS_FILE.parent.mkdir(parents=True, exist_ok=True)
    REQUIREMENTS_FILE.write_text(requirements, encoding="utf-8")


def main():
    print("=" * 60)
    print(" Local AI Voice Studio - Hardware Detection")
    print("=" * 60)
    print()

    cpu = detect_cpu()
    ram = detect_ram()
    nvidia = detect_nvidia()
    capability = detect_cuda_capability()

    backend = choose_backend(nvidia)

    config = {
        "cpu": cpu,
        "ram_gb": ram,
        "gpu_name": nvidia["name"],
        "vram_gb": nvidia["vram_gb"],
        "nvidia_driver": nvidia["driver"],
        "cuda_compute_capability": capability,
        "backend": backend["backend"],
        "torch_version": backend["torch_version"],
        "torchaudio_version": backend["torchaudio_version"],
        "torch_index_url": backend["torch_index_url"],
    }

    print(f"CPU:             {cpu}")
    print(f"RAM:             {ram} GB")

    if nvidia["available"]:
        print(f"GPU:             {nvidia['name']}")
        print(f"VRAM:            {nvidia['vram_gb']} GB")
        print(f"NVIDIA Driver:   {nvidia['driver']}")

        if capability:
            print(f"Compute Cap:     {capability}")

        print()
        print("Backend:          NVIDIA CUDA")
        print(f"PyTorch:         {backend['torch_version']}")
        print("CUDA Runtime:    12.4")

    else:
        print("GPU:             None / NVIDIA GPU not detected")
        print()
        print("Backend:          CPU")
        print(f"PyTorch:         {backend['torch_version']}")

    print()
    print("Generating requirements.txt...")

    generate_requirements(config)

    print(f"Generated: {REQUIREMENTS_FILE}")

    # Save hardware configuration
    config_file = PROJECT_ROOT / "hardware_config.json"

    config_file.write_text(
        json.dumps(config, indent=2),
        encoding="utf-8",
    )

    print(f"Hardware config: {config_file}")

    print()
    print("=" * 60)
    print(" Hardware Detection Complete")
    print("=" * 60)


if __name__ == "__main__":
    main()